name: "dojo"

on:
  workflow_dispatch:  
jobs:
  dojo:
    runs-on:
      - self-hosted
      - linux
      - x64
      - non-prod
    steps:
      - name: Run Deployment Ps Script
        shell: pwsh
        run: |
            dotnet build

