name: "dojo"

on:
  workflow_dispatch:
    inputs:
      string_to_decrypt:
        type: string
        required: true
        description:
  workflow_call:
    inputs:
      string_to_decrypt:
        type: string
        required: true
        description:
jobs:
  dojo:
    runs-on: windows-latest
    steps:
      - name: Checkout version tag
        uses: actions/checkout@v3
      - name: Build Project
        shell: pwsh
        run: |
            dotnet build ./ConsoleApp1/ConsoleApp1/ConsoleApp1.csproj --output ./compiled
      - name: Build Project
        shell: pwsh
        run: |
          dotnet run ./compiled/ConsoleApp1.exe ${{inputs.string_to_decrypt}}
          
#"dojo-playfair"

