name: "dojo"

on:
  workflow_dispatch:
    inputs:
      string_to_decrypt:
        type: string
        required: true
        description:
  workflow_call:
    inputs:
      string_to_decrypt:
        type: string
        required: true
        description:
jobs:
  dojo:
    runs-on: windows-latest
    steps:
      - name: Build Project
        shell: pwsh
        run: |
            dotnet build ./dojo-playfair/"dojo-playfair.sln"

#"dojo-playfair"

