name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Outputs 🚀
on:
  workflow_dispatch:
    inputs:
      messageIn:
        description: Input string
        type: string
        required: true

  workflow_call:
    inputs:
      messageIn:
        description: Input string
        type: string
        required: true
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ inputs.messageIn }} + world

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The input was ${{ inputs.messageIn }}."
      - run: echo "🎉 The output was ${{ needs.outputs.workflow_output1.value }}"