name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Inputs 🚀
on:
  workflow_dispatch:
    inputs:
      messageIn:
        description: Input string
        type: string
        required: true

  workflow_call:
    inputs:
      messageIn:
        description: Input string
        type: string
        required: true

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The input was ${{ inputs.messageIn }} event."